


try{
console.log(naoExisto)
}catch(err){
    console.log('NÃ£o existo')
}